import type { NextPage } from "next";
import Head from "next/head";
import Hero from "@/components/Banner/HeroBanner";
import { Header } from "@/components/Header/Header";
import { CardInfo } from "@/components/Banner/CardInfo";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />

      <main className="mx-auto max-w-screen-xl px-6 sm:px-8">
        <div className="mt-16 space-y-20">
          <CardInfo />
        </div>
      </main>

      <p className="text-3xl">Home Page</p>
    </>
  );
};

export default Home;
