import type { NextPage } from "next";
import Head from "next/head";
import { Hero } from "../components/Hero";
import { Header } from "../components/Header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <p className="text-3xl">Home Page</p>
    </>
  );
};

export default Home;
